
package client.controllers;

/**
 *
 * @author fatma
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.11 at 10:16:43 PM EET 
//



import SaveChat.*;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the demo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Chathistory_QNAME = new QName("", "chathistory");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: demo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ChathistoryType }
     * 
     */
    public ChathistoryType createChathistoryType() {
        return new ChathistoryType();
    }

    /**
     * Create an instance of {@link MsgType }
     * 
     */
    public MsgType createMsgType() {
        return new MsgType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChathistoryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "chathistory")
    public JAXBElement<ChathistoryType> createChathistory(ChathistoryType value) {
        return new JAXBElement<ChathistoryType>(_Chathistory_QNAME, ChathistoryType.class, null, value);
    }

}


